# Generated by Django 5.0.7 on 2024-10-13 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(default='não informado!', max_length=50)),
                ('registro_curs', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('cpf', models.CharField(default='', max_length=50)),
                ('telefone', models.CharField(default='', max_length=50)),
                ('nascimento', models.DateField()),
                ('registro_client', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='turmas_formatec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turmas_formatec', models.CharField(default='não informado!', max_length=40)),
                ('registro_turms', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='financas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ori', models.CharField(default=' ', max_length=50)),
                ('cliente', models.CharField(default=' ', max_length=100)),
                ('parcela', models.CharField(default=' ', max_length=100)),
                ('valor', models.CharField(default=' ', max_length=100)),
                ('vencimento', models.DateField(null=True)),
                ('data_pagamento', models.DateField(null=True)),
                ('banco', models.CharField(default=' ', max_length=50)),
                ('arquivo', models.FileField(blank=True, default=' ', upload_to='media/')),
                ('registro_fin', models.DateField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financas_online.cursos')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financas_online.turmas_formatec')),
            ],
        ),
    ]
