# Generated by Django 5.0.7 on 2024-10-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financas',
            name='parcela',
            field=models.CharField(choices=[(1, 1), (2, 2)], default=' ', max_length=100),
        ),
    ]
