# Generated by Django 5.0.7 on 2024-10-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_online', '0002_alter_financas_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financas',
            name='parcela',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
