# Generated by Django 5.0.7 on 2024-10-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_online', '0003_alter_financas_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='financas',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='curso',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='financas',
            name='arquivo',
            field=models.FileField(blank=True, default='', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='financas',
            name='banco',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='financas',
            name='cliente',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='financas',
            name='id_ori',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='financas',
            name='parcela',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='financas',
            name='valor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='turmas_formatec',
            name='turmas_formatec',
            field=models.CharField(default='', max_length=40),
        ),
    ]
