# Generated by Django 5.0.7 on 2024-10-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_online', '0004_financas_status_alter_cursos_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financas',
            name='status',
            field=models.CharField(default='Pendente', max_length=100),
        ),
    ]
