# Generated by Django 5.0.7 on 2024-10-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_online', '0006_alter_financas_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financas',
            name='status',
            field=models.CharField(default='A receber', max_length=100),
        ),
    ]
