# Generated by Django 5.0.7 on 2024-11-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_online', '0014_alter_financas_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financas',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/'),
        ),
        migrations.AlterField(
            model_name='financas',
            name='curso',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='financas',
            name='turma',
            field=models.CharField(default='', max_length=100),
        ),
    ]
