# Generated by Django 5.0.7 on 2024-11-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas_online', '0016_alter_financas_curso_alter_financas_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='financas',
            name='tipo_pagamento',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='financas',
            name='valor',
            field=models.IntegerField(default='', null=True),
        ),
    ]
