name: Deploy Django App

on:
  push:
    branches:
      - main  # ou qualquer que seja o branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'  # substitua pela versão do Python que você está usando

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test
                  
      - name: Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/private_key
          chmod 600 /tmp/private_key
          
          rsync -e 'ssh -i /tmp/private_key' -avz --exclude='*.git*' . $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH

          ssh -i /tmp/private_key $REMOTE_USER@$REMOTE_HOST << 'EOF'
            cd $REMOTE_PATH
            10_Django\Scripts\activate  # ou o comando apropriado para ativar seu ambiente virtual
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            python manage.py runserver  # substitua pelo comando apropriado para reiniciar seu serviço
          EOF
